name: clean_trivia
description: A number trivia app with clean architecture

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  connectivity: ^2.0.1
  cupertino_icons: ^0.1.3
  dartz: ^0.9.2
  equatable: ^1.2.5
  flutter_bloc: ^6.1.0
  get_it: ^5.0.1
  http: ^0.12.2
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.0
  very_good_analysis: ^1.0.3

flutter:
  uses-material-design: true
