name: network_info
description: Dart package which manages network connectivity.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  connectivity: ^2.0.1
  equatable: ^1.2.0
  meta: ^1.1.8
  very_good_analysis: ^1.0.3
