name: number_trivia
description: Dart package which manages number trivia's domain and data.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  errors:
    path: ../errors
  network_info:
    path: ../network_info

  dartz: ^0.9.2
  dio: ^3.0.10
  equatable: ^1.2.0
  meta: ^1.1.8
  very_good_analysis: ^1.0.3
